### ISSUE TITLE
Not compatible with neo 0.5 ?

### ISSUE THREAD

**Issue by eackermann** [OpenElectrophy/OpenElectrophy#26]
It seems like OpenElectrophy is only compatible with NEO 0.4; are there any plans to bring this up to date?

**Comment by samuelgarcia** [comment]
Yes that is true.

The object model in neo >=0.5 have change and so OpenElectrophy need a strong change to be compatible with new version of neo.

Since there are also lot of other strong changes everywhere (py2>py3, new sqlalchemy,  Qt4>Qt5, remove the spike sorting and use tridesclous instead, rewritte viewers ...), there are no plan to be compatible with neo 0.5

I am in a process of breaking OE in small pieces. When this will be done maybe one day, I will refactor OE based of those pieces.

Best.

**Comment by eackermann** [comment]
Thanks! I've found tridesclous, and will check it out...
